export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'

export const FETCH_CITIES = 'FETCH_CITIES'

export const SHORTLIST_TOGGLE = 'SHORTLIST_TOGGLE'

export const REMOVE_CITY = "REMOVE_CITY"
